[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "flet>=0.27.6",
    "spacy>=3.0.0",
    "langdetect>=1.0.9"
]